name: Update ChinaList-For-AdguardHome

on:
   workflow_dispatch:
   schedule:
     - cron: '0 12 * * *'

jobs:
  update_dns_list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        chmod +x script.sh
        ./script.sh
- name: Commit and Push
    run: |
      git config user.name "fengqyv5"
      git config user.email "fengqyv5@github.com"

    # 添加更改
      git add .

    # 提交更改
      git commit -m "Automated processing and merging of txt files" || echo "No changes to commit"

    # 推送到仓库（需要权限）
      git push origin HEAD
