name: Update ChinaList-For-AdguardHome

on:
   workflow_dispatch:
   schedule:
     - cron: '0 12 * * *'

jobs:
  update_dns_list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        chmod +x script.sh
        ./script.sh
    - name: Commit and Push
      run: |
        git config user.name "fengqyv5"
        git config user.email "fengqyv5@github.com"
        git add .
        git commit -m "Automated update ChinaList-For-AdguardHome" || echo "No changes to commit"
        git push origin HEAD
